name: Bug Report
description: Report a bug or issue with MarkView
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the information below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Open a markdown file
        2. Click on...
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MarkView Version
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Edge
        - Brave
        - Opera
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Screenshots, console errors, or anything else that might help
      placeholder: Optional - Add any extra context here
