name: Feature Request
description: Suggest an idea or enhancement for MarkView
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
      description: Describe your idea clearly
      placeholder: I would like MarkView to...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      description: Explain the use case or problem this solves
      placeholder: This would help when...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details, examples, or screenshots
      placeholder: Optional - Add mockups, examples, or links to similar features
